#!/bin/python
#
# $Header: ecs/exacloud/exabox/exatest/cluctrl/shared_methods/tests_exacc_cprops_fedramp.py /main/1 2024/10/10 02:31:14 jfsaldan Exp $
#
# tests_exacc_cprops_fedramp.py
#
# Copyright (c) 2024, Oracle and/or its affiliates.
#
#    NAME
#      tests_exacc_cprops_fedramp.py - <one-line expansion of the name>
#
#    DESCRIPTION
#      <short description of component this file declares/defines>
#
#    NOTES
#      <other useful comments, qualifications, etc.>
#
#    MODIFIED   (MM/DD/YY)
#    jfsaldan    10/02/24 - Bug 37081598 - EXACC:BB:FEDRAMP: COMMON_FEDRAMP
#                           SHOULD BE ENABLED ON
#                           /VAR/OPT/ORACLE/CPROPS/CPROPS.INI
#    jfsaldan    10/02/24 - Creation
#

import unittest
from unittest.mock import patch
from exabox.exatest.common.ebTestClucontrol import ebTestClucontrol
from exabox.core.Node import exaBoxNode
from exabox.core.MockCommand import exaMockCommand
from exabox.log.LogMgr import ebLogInfo
from exabox.core.Error import ExacloudRuntimeError

class ebTestExaCCFedRampCprops(ebTestClucontrol):

    @classmethod
    def setUpClass(self):
        super().setUpClass(aUseOeda=False)
        self.maxDiff = None

    def test_mEnsureFedRampCpropsIni_enabled(self):
        """
        Function to mock and test mEnsureFedRampCpropsIni
        """

        _cmds = {
            self.mGetRegexVm(): [
                [
                    exaMockCommand(
                        "/bin/test -e /var/opt/oracle/cprops/cprops.ini",
                        aStdout="", aRc=0),
                    exaMockCommand(
                        "/bin/cat /var/opt/oracle/cprops/cprops.ini",
                        aStdout=(
            "#################################################################"
            "# This file is automatically generated by database as a service #"
            "#                                                               #"
            "# Do not edit contents in this file, Thanks!                    #"
            "#                                                               #"
            "#################################################################"
            "_localmetadata=False"
            "adb_s_enabled=False"
            "cns_enabled=False"
            "common_drcc_dns_suffix=oraclerealm5.com"
            "common_fedramp=disabled"
            "common_fips_compliance=enabled"
            "common_nat_fileserver=patchserver"
            "common_nat_fileserver_port=2080"
            "common_nat_proxy_port=3080"
            "common_oss_url=https://swiftobjectstorage.us-tacoma-1.oraclecloud5.com"
            "common_se_linux=enforcing"
            "diag_srvrs="
            "localmetadata=False"
            "ords_enable=False"
            "wallet_loc=/u01/app/oracle/admin/cprops/cprops_wallet"
                            ), aRc=0),
                    exaMockCommand(
                        "/bin/cat /var/opt/oracle/cprops/cprops.ini",
                        aStdout=(
            "#################################################################"
            "# This file is automatically generated by database as a service #"
            "#                                                               #"
            "# Do not edit contents in this file, Thanks!                    #"
            "#                                                               #"
            "#################################################################"
            "_localmetadata=False"
            "adb_s_enabled=False"
            "cns_enabled=False"
            "common_drcc_dns_suffix=oraclerealm5.com"
            "common_fedramp=enabled"
            "common_fips_compliance=enabled"
            "common_nat_fileserver=patchserver"
            "common_nat_fileserver_port=2080"
            "common_nat_proxy_port=3080"
            "common_oss_url=https://swiftobjectstorage.us-tacoma-1.oraclecloud5.com"
            "common_se_linux=enforcing"
            "diag_srvrs="
            "localmetadata=False"
            "ords_enable=False"
            "wallet_loc=/u01/app/oracle/admin/cprops/cprops_wallet"
                            ), aRc=0),
                    exaMockCommand(
                        "/bin/cat /var/opt/oracle/cprops/cprops.ini",
                        aStdout=(
            "#################################################################"
            "# This file is automatically generated by database as a service #"
            "#                                                               #"
            "# Do not edit contents in this file, Thanks!                    #"
            "#                                                               #"
            "#################################################################"
            "_localmetadata=False"
            "adb_s_enabled=False"
            "cns_enabled=False"
            "common_drcc_dns_suffix=oraclerealm5.com"
            "common_fedramp=disabled"
            "common_fips_compliance=enabled"
            "common_nat_fileserver=patchserver"
            "common_nat_fileserver_port=2080"
            "common_nat_proxy_port=3080"
            "common_oss_url=https://swiftobjectstorage.us-tacoma-1.oraclecloud5.com"
            "common_se_linux=enforcing"
            "diag_srvrs="
            "localmetadata=False"
            "ords_enable=False"
            "wallet_loc=/u01/app/oracle/admin/cprops/cprops_wallet"
                            ), aRc=0),
                ],
            ]
        }

        self.mPrepareMockCommands(_cmds)
        _ebox = self.mGetClubox()
        _options = self.mGetPayload()
        _options.jsonconf["dbaas_api"] = {
                "params": {
                    "common": {
                        "fedramp": "enabled"}}}


        self.assertEqual(0,
            _ebox.mEnsureFedRampCpropsIni(
                _ebox.mReturnDom0DomUPair(), _options))

    def test_mEnsureFedRampCpropsIni_disabled(self):
        """
        Function to mock and test mEnsureFedRampCpropsIni
        """

        _cmds = {
            self.mGetRegexVm(): [
                [
                    exaMockCommand(
                        "/bin/test -e /var/opt/oracle/cprops/cprops.ini",
                        aStdout="", aRc=0),
                ]
            ]
        }

        self.mPrepareMockCommands(_cmds)
        _ebox = self.mGetClubox()
        _options = self.mGetPayload()
        _options.jsonconf["dbaas_api"] = {
                "params": {
                    "common": {
                        "fedramp": "disabled"}}}


        self.assertEqual(1,
            _ebox.mEnsureFedRampCpropsIni(
                _ebox.mReturnDom0DomUPair(), _options))

if __name__ == "__main__":
    unittest.main(warnings='ignore')
