"""
 Copyright (c) 2019, 2025, Oracle and/or its affiliates.

NAME:
    cs_postdbinstall.py - Create Service POST DB INSTALL

FUNCTION:
    Implements the post DB install for create service execution

NOTES:
    Invoked from cs_driver.py

EXTERNAL INTERFACES: 
    csPostDBInstall         ESTP_POSTDB_INSTALL

INTERNAL CLASSES:

History:
    srtata      04/23/2019 - 29556301: implement doExecute
    dekuckre    04/05/2019 - Creation

"""

import time
from exabox.core.Error import ebError, ExacloudRuntimeError
from exabox.log.LogMgr import ebLogError, ebLogInfo, ebLogWarn, ebLogDebug, ebLogVerbose
from exabox.ovm.csstep.cs_constants import csConstants
from exabox.ovm.csstep.cs_base import CSBase
from exabox.ovm.csstep.cs_util import csUtil
from exabox.ovm.utils.clu_utils import ebCluUtils
import time

# This class implements doExecute and undoExecute functions
# for the ESTP_POSTDB_INSTALL step of create service
class csPostDBInstall(CSBase):
    def __init__(self):
        self.__step = 'ESTP_POSTDB_INSTALL'

    def doExecute(self, aExaBoxCluCtrlObj, aOptions, steplist):
        ebLogInfo('csPostDBInstall: Entering doExecute')
        ebox = aExaBoxCluCtrlObj
        ebox.mUpdateStatus('createservice step '+self.__step)
        _clu_utils = ebCluUtils(ebox)
        _stepSpecificDetails = _clu_utils.mStepSpecificDetails("createServiceDetails", 'ONGOING', "Post DB Install in progress", 'ESTP_POSTDB_INSTALL')
        _clu_utils.mUpdateTaskProgressStatus([], 0, "Post DB Install", "In Progress", _stepSpecificDetails)

        if ebox.mIsFedramp():
            # As per FedRAMP requirement, remove the VM keys (of 'root','oracle','opc','grid')
            # stored and generated by Exacloud.
            ebox.mPostDBSSHKeyPatching(aOptions, 'deletekey', ['root','oracle','opc','grid'])
           
            ebox.mRemoveExacloudVMKeys()
            ebLogInfo("FedRAMP: Removed access to domUs for root, oracle, opc and grid.")

        ebLogInfo('*** Exacloud Operation Successful : POST DB Install')
        ebLogInfo('csPostDBInstall: Completed doExecute Successfully')
        _stepSpecificDetails = _clu_utils.mStepSpecificDetails("createServiceDetails", 'DONE', "Post DB Install Completed", 'ESTP_POSTDB_INSTALL')
        _clu_utils.mUpdateTaskProgressStatus([], 100, "Post DB Install", "Done", _stepSpecificDetails)

    def undoExecute(self, aExaBoxCluCtrlObj, aOptions, steplist):
        _ebox = aExaBoxCluCtrlObj

        ebLogInfo('csPostDBInstall: Entered undoExecute')
        _clu_utils = ebCluUtils(_ebox)
        _stepSpecificDetails = _clu_utils.mStepSpecificDetails("deleteServiceDetails", 'ONGOING', "Undo Post DB Install in progress", 'ESTP_POSTDB_INSTALL')
        _clu_utils.mUpdateTaskProgressStatus([], 0, "Undo Post DB Install", "In Progress", _stepSpecificDetails)


        #
        # Special Cases
        #
        _ebox.mBug23715436()

        db_step_list = [csConstants.OSTP_APPLY_FIX, csConstants.OSTP_CREATE_PDB, csConstants.OSTP_CREATE_DB, csConstants.OSTP_CREATE_ASM, csConstants.OSTP_RELINK_DB, csConstants.OSTP_INSTALL_DB]
        for step in db_step_list:

            if step == csConstants.OSTP_CREATE_PDB and not _ebox.mIsCdbPdb():
                continue

            if step == csConstants.OSTP_APPLY_FIX and _ebox.mCheckConfigOption('skip_afs_step','True'):
                continue

            try:
                _csu = csUtil()
                _csu.mExecuteOEDAStep(_ebox, self.__step, steplist, aOedaStep=step, undo=True)
            except:
                ebLogWarn('*** Warning *** : Last step (%s) did not complete successfully - Continue with next step in undo mode' % (step))

        _step_time = time.time()
        _ebox.mUpdateStatusCS(True, self.__step, steplist, aComment = 'Running External POSTDB Scripts')
        _ebox.mRunScript(aType='*',aWhen='post.db_delete')
        _rc = _ebox.mRemoveGridListener()
        if not _rc:
            ebLogWarn('*** Warning *** Error in removing grid listener file- ignoring in undo mode')

        _ebox.mRollbackEncryption(aOptions.jsonconf)
        _ebox.mLogStepElapsedTime(_step_time, 'POSTDB DELETE: Running External Scripts')

        ebLogInfo('csPostDBInstall: Completed undoExecute Successfully')
        _stepSpecificDetails = _clu_utils.mStepSpecificDetails("deleteServiceDetails", 'DONE', "Undo Post DB Install Completed", 'ESTP_POSTDB_INSTALL')
        _clu_utils.mUpdateTaskProgressStatus([], 100, "Undo Post DB Install", "Done", _stepSpecificDetails)

