"""
 Copyright (c) 2018, 2025, Oracle and/or its affiliates.

NAME:
    cluexaccsecrets.py - Logic to package a secret and push it to domU specific to exacc OCI

FUNCTION:
    Setup CPS IB

NOTE:

History:

    MODIFIED   (MM/DD/YY)
       jfsaldan 05/30/25 - Bug 37945713 - ADBD: OBSERVING WRONG PERMISSIONS IN
                           /OPT/EXACLOUD DIRECTORY FOR FILES ATP.INI,
                           NODES.JSON AND GET_CS_DATA.PY
       naps     04/17/25 - 37508678 - Update exacli password in parallel for
                           domu.
       ajayasin 11/11/21 - alter user exacli password update on domUs
       ndesanto 10/02/19 - Enh 30374491: EXACC PYTHON 3 MIGRATION BATCH 02
       vgerard  07/06/19 - Creation 
"""

from subprocess import Popen, PIPE
import six
import tempfile
import string
import json
import os
from exabox.tools.AttributeWrapper import wrapStrBytesFunctions
from exabox.core.Error import ExacloudRuntimeError
from exabox.core.Node import exaBoxNode
from exabox.core.Context import get_gcontext
from exabox.log.LogMgr import ebLogInfo, ebLogError, ebLogDebug, ebLogWarn
from exabox.BaseServer.AsyncProcessing import ProcessManager, ProcessStructure, TimeoutBehavior, ExitCodeBehavior

class ebExaCCSecrets(object):
    """ Class to manage the Exacli password push to dom0 for ExaCCOCI """


    def __init__(self, aDomUs, aDebug=False, aMode=True):
        """ Constructor

        :param list aDomUs:
            Iterable of domUs for pushing the keys.

        :param bool aDebug:
            Boolean to activate extra logging (KEY WILL BE LOGGED).

        :param bool aMode:
            test Mode need an explicit set to False.
        """

        self.__domUs  = aDomUs
        self.__debug  = aDebug
        self.__aMode  = aMode

    def mPushExacliPasswdToDomUs(self, aPasswd,aUser=None):
        """ 
            Main entry point to push the ExaCli password in encrypted form
            to all domUs.

            :param str aPasswd: ExaCli clear text password
        """
        _key = self.mGeneratePassKey()
        # We encrypt this Dictionary below
        if aUser:
            _data = {'desc':'ExaCli changed password is:', 'data':aPasswd}
        else:
            _data = {'desc':'ExaCli initial password is:', 'data':aPasswd}
        # in JSON form
        _encryptedData = self.mEncryptData(json.dumps(_data), _key)
        ebLogInfo('*** Encrypted Exacli password, sending it to domUs')

        _remote_key_file   = '/home/opc/cs_key'
        _remote_script_loc = '/opt/exacloud/get_cs_data.py'
        _remote_data_loc   = '/opt/exacloud/cs_data.enc'

        def _mPushExacliPwd(aDomu):
            _domU = aDomu
            _node = exaBoxNode(get_gcontext())
            if aUser:
                _node.mSetUser(aUser)
            _node.mConnect(aHost=_domU)
            ebLogInfo('*** Sending Exacli secrets to domU:{}'.format(_domU))
            self.mWriteDataToFileOnNode(_node, _key, _remote_key_file)
            self.mSecureFileOnNode(_node,_remote_key_file)
            self.mWriteDataToFileOnNode(_node, _encryptedData, _remote_data_loc)
            self.mSecureFileOnNode(_node,_remote_data_loc)
            self.mSendDecryptScriptToNode(_node,_remote_script_loc)
            self.mSecureFileOnNode(_node,_remote_script_loc,aMode="551")
            _node.mDisconnect()
        _plist = ProcessManager()
        for _domU in self.__domUs:
            _p = ProcessStructure(_mPushExacliPwd, [_domU])
            _p.mSetMaxExecutionTime(60*60)
            _p.mSetJoinTimeout(5)
            _p.mSetLogTimeoutFx(ebLogWarn)
            _plist.mStartAppend(_p)
        _plist.mJoinProcess()


    def mGeneratePassKey(self):
        """ 
        Generates a key to use with OpenSSL -k option.
        Key need to have a good entropy/size as AES key/iv derivation
        in OpenSSL is very basic

        :return:
            A String of printable Characters, at least 64 bytes long
        :rtype: str
        """

        _final = ''
        #At least 64 Bytes as OpenSSL key derivation is basic
        while (len(_final) < 64): 
            #Get 128 Bytes of randomness from the OS crypto device (urandom)
            _rand = os.urandom(128)
            # Modulo 127 for ASCII range
            _final = [chr((x if isinstance(x, int) else ord(x)) % 127) for x in _rand]
            _final = ''.join([x for x in _final if x in string.printable and x not in string.whitespace])
        # Example Key generated by code above: (typically around ~90Bytes)
        # VADb\'UxZ~E&#o=e?7oWJ)4O7du:;1^l=z.]WP2p50t/fAWF4tJR7|v~%cZ7bK2:Ob~}dVd|BJZ:\'Jx[rZ~ydNo"cpDt,0L
        return _final

    def mEncryptData(self, aInput, aKey):
        """ Encrypts the data with openssl AES-256-CBC

        :param str aInput:
            Data to encrypt
        :param str aKey:
            Key argument for openssl -k option
        :return:
            Output String in Base64 (-a option passed to OpenSSL)
        :rtype: str
        """

        _cmd = ['openssl','enc','-a','-aes-256-cbc','-md','sha512','-pass','env:K']
        _p = Popen(_cmd, shell=False,stderr=PIPE,stdin=PIPE,stdout=PIPE, env={'K':aKey})
        _out,_err = wrapStrBytesFunctions(_p).communicate(input=aInput.encode('utf8'))
        if self.__debug:
            ebLogDebug('Cmd: {}, Key: {}, Stdout: {}, Stderr: {}'.format(' '.join(_cmd), aKey, _out,_err))
        if _p.returncode != 0:
            _msg = 'Error while generating the openssl encrypted Exacli for ExaCC OCI. Retcode: {}, stderr:{}'.format(_p.returncode, _err)
            ebLogError('*** {}'.format(_msg))
            raise ExacloudRuntimeError(0x0113, 0xA, _msg)
        return _out


    def mWriteDataToFileOnNode(self, aNode, aData, aDestFile):
        """ Writes Data To File on connected Node

        :param obj aNode: Node with open connection (to domU)

        :param str aData: Data to write to the file

        :param str aDestFile: Destination File name on DomUs
        """
        with tempfile.NamedTemporaryFile(delete=False) as tfile:
            tfile.write(six.ensure_binary(aData))
            tfile.close()
            aNode.mCopyFile(tfile.name, aDestFile)
            os.unlink(tfile.name)

    def mSendDecryptScriptToNode(self, aNode, aRemotePath):
        """ Sends Decrypt Script to Node (DomU)

        :param obj aNode: Node with open connection (to domU)

        :param str aRemotePath
            Path to copy the decryption script to.
        """
        aNode.mCopyFile('./scripts/exaccsecret/get_cs_data.py',aRemotePath)
        aNode.mExecuteCmd('chmod a+x {}'.format(aRemotePath))

    def mSecureFileOnNode(self, aNode, aRemotePath, aOwner='opc', aMode=0o600):
        """ Set owner and mode on file

        :param obj aNode: Node with open connection (to domU)

        :param str aRemotePath: Path of the Remote file

        :param str aOwner: (optional) (default:'opc')

        :param oct aMode: (optional) (default:0600)
        """
        aNode.mExecuteCmd('chown {} {}'.format(aOwner, aRemotePath))
        aNode.mExecuteCmd('chmod {} {}'.format(aMode, aRemotePath))
