"""
 Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.

NAME:
    clusteps.py - Create Service stepwise steps
FUNCTION:

NOTES:

EXTERNAL INTERFACES:

History:
    dekuckre  04/05/2019 - Include Create Service steps

"""

ESTP_PREVM_CHECKS   = "ESTP_PREVM_CHECKS"
ESTP_PREVM_SETUP    = "ESTP_PREVM_SETUP"
ESTP_CREATE_VM      = "ESTP_CREATE_VM"
ESTP_POSTVM_INSTALL = "ESTP_POSTVM_INSTALL"
ESTP_CREATE_USER    = "ESTP_CREATE_USER"
ESTP_CREATE_STORAGE = "ESTP_CREATE_STORAGE"
ESTP_INSTALL_CLUSTER= "ESTP_INSTALL_CLUSTER"
ESTP_POSTGI_INSTALL = "ESTP_POSTGI_INSTALL"
ESTP_POSTGI_NID     = "ESTP_POSTGI_NID"

